# Generated by Django 4.0.10 on 2023-07-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albumThumbnail',
            new_name='songThumbnail',
        ),
    ]
